### ISSUE TITLE
Add raw data to this repository

### ISSUE THREAD

**Issue by Wu-Urbanek** [cldf-datasets/dryerorder#1]
May I add a raw data to this repository?

**Comment by SimonGreenhill** [comment]
yes please!

**Comment by xrotwang** [comment]
Link to article: https://doi.org/10.1353/lan.2018.0054

**Comment by xrotwang** [comment]
@MacyL How did you get [Dryer2018_msw.csv](raw/Dryer2018_msw.csv)? It seems to have data on ~20 more languages than the source paper.

**Comment by Wu-Urbanek** [comment]
If I remember it correctly, I downloaded the data from the supplementary.
https://muse.jhu.edu/article/712564

In his article, he said this in the footnote: 
The sample of languages is a convenience sample, made up of those languages from my larger typological database (much of it represented in my chapters in Dryer & Haspelmath 2013) for which I have data on the order of these four elements and for which a single order is dominant. Additional information about the sample and other supplementary materials accompanying this article can be accessed online at http://muse.jhu.edu/resolve/54.

**Comment by xrotwang** [comment]
Ah, ok. Thanks! So this dataset is another one that starts out with a puzzle :) While the PDF supplement talks about a "576 language sample", the data file has 594 languages with a value for the word order type ...
Martin Haspelmath sent me a data file with the correct number - but I would say the right thing to do is starting out with the official download as you did.

**Comment by Wu-Urbanek** [comment]
I don't mind to go through the list and do some annotation or corrections. It was a fun dataset for me to play around with java script and APIs. 
Let me know how to proceed :)
